name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ybrenning/fhpmensa:$(date +%s)
    
    - name: Publish Docker
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: ybrenning/fhpmensa
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}

