name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run Docker
      run: |
        echo ${{secrets.USERNAME}} | sed 's/./& /g' 
        docker login -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }}
        docker container run --env ${{ secrets.BOT_TOKEN }} --env ${{ secrets.CHAT_ID }}fhpmensa:latest

